apiVersion: v1
kind: Secret
metadata:
  name: {{.Release.Name}}
  labels:
    release: {{.Release.Name}}
type: Opaque
data:
  db_user: {{.Values.mysql.db_user| b64enc}}
  db_password: {{.Values.mysql.db_password | b64enc}}
  client_secrets.json: |
{{ .Files.Get "client_secrets.json" | b64enc | indent 4}}